spring:
  profiles:
    active: test #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

server:
  port: 8001

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:/mapper/*.xml




