spring:
  profiles:
    active: test #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

server:
  port: 8001

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:/mapper/*.xml

jwt:
  tokenHeader: Authorization
  secrect: mall-portal-secret
  expiration: 604800 # 60*60*24*7
  tokenHead: Bearer

secure:
  ignored:
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /webjars/springfox-swagger-ui/**
    - /druid/**
    - /actuator/**
    - /hello

